pipeline {
    agent any

    environment {
        IMAGE_NAME = "usmaan123/springboot-app"
        IMAGE_TAG = "latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
    steps {
        dir('complete') {
            sh 'chmod +x mvnw'
            sh './mvnw clean package'
        }
    }
}

        stage('Build Docker Image') {
    steps {
        dir('complete') {
            sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
        }
    }
}

        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
            }
        }
    }

    post {
        success {
            echo 'Pipeline Executed Successfully'
        }

        failure {
            echo 'Pipeline Failed'
        }
    }
}